// Contains all data for Artifacts.
const artifactsData = [
  {
    "name": "Admiral's Hat",
    "effect": "No boarding or unboarding penalty for boats. Allows casting Summon Boat and Scuttle Boat at Expert level. Protects from whirlpools. Increases movement points at sea by 1500.",
    "slot": "Helmet, Necklace",
    "related_artifacts": "Sea Captain's Hat, Necklace of Ocean Guidance",
    "class": "Combination",
    "cost": "25000 G",
    "event_description": "You trip over the Admiral's Hat, dust it off, and stick it in your pack.",
    "component_of": null
  },
  {
    "name": "Amulet of the Undertaker",
    "effect": "+2.5% Necromancy. If the equipped hero does not have the Necromancy secondary skill, the Amulet of the Undertaker has no effect.",
    "slot": "Necklace",
    "related_artifacts": "Cloak of the Undead King, Vampire's Cowl, Dead Man's Boots",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "A dirty amulet lies next to a freshly dug grave. Upon investigation, you discover it to be the enchanted Amulet of the Undertaker, long thought lost by mortals.",
    "component_of": "Cloak of the Undead King"
  },
  {
    "name": "Angelic Alliance",
    "effect": "+21 to all Primary Skills. Allows casting of expert Prayer at the beginning of each combat round for 10 rounds. The artifact also negates any morale penalty for having creatures of different alignments (Good and Neutral) in the army, providing a +1 Morale bonus instead.",
    "slot": "Helm, Necklace, Torso, Feet, Weapon, Shield",
    "related_artifacts": "Helm of Heavenly Enlightenment, Celestial Necklace of Bliss, Armor of Wonder, Sandals of the Saint, Sword of Judgement, Lion's Shield of Courage",
    "class": "Combination",
    "cost": "84000 G",
    "event_description": "You trip over the Angelic Alliance, dust it off, and stick it in your pack.",
    "how_it_works": "The prayer ability can be impacted by creature immunities, Cursed Ground, or anti-magic artifacts, but functions in Anti-Magic Garrisons. The hero Loynis' specialty enhances the Prayer effect cast by the artifact. Neutral creatures are not considered neutrally aligned for the morale bonus.",
    "gameplay_analysis": "The Angelic Alliance provides the highest primary skill boosts of any combination artifact, surpassing the Power of the Dragon Father while using only 6 slots compared to 9. It is also the most expensive artifact in \"The Shadow of Death\".",
    "component_of": null
  },
  {
    "name": "Armor of the Damned",
    "effect": "+3 Attack, +3 Defense, +2 Spell Power, +2 Knowledge. Casts expert Slow, Curse, Weakness, and Misfortune on all enemy units for 50 rounds at the start of combat.",
    "slot": "Helmet, Torso, Weapon, Shield",
    "related_artifacts": "Skull Helmet, Rib Cage, Blackshard of the Dead Knight, Shield of the Yawning Dead",
    "class": "Combination",
    "cost": "12000 G",
    "event_description": "You trip over the Armor of the Damned, dust it off, and stick it in your pack.",
    "how_it_works": "The spells are cast once an allied creature is able to take its turn. If a creature misses a turn due to low morale, the spells are not cast until the next creature's turn. The specialties of heroes Cuthbert, Olema, Mirlanda, and Eanswythe will enhance the Weakness spell cast by the armor.",
    "gameplay_analysis": "While its stat boosts are among the weakest for a combination artifact, its effect is one of the most powerful, casting four expert-level spells for free. Of the spells cast, Slow is excellent, while Weakness and Curse are potent when combined; only Misfortune is subpar.",
    "component_of": null
  },
  {
    "name": "Armor of Wonder",
    "effect": "+1 Attack, +1 Defense, +1 Spell Power, +1 Knowledge.",
    "slot": "Torso",
    "related_artifacts": "Angelic Alliance, Helm of Heavenly Enlightenment, Celestial Necklace of Bliss, Sandals of the Saint, Sword of Judgement, Lion's Shield of Courage",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "A gang of Rogues is sifting through the possessions of dead warriors. Scaring off the scavengers, you note the Rogues had overlooked a dirty, but serviceable, breastplate.",
    "component_of": "Angelic Alliance"
  },
  {
    "name": "Armageddon's Blade",
    "effect": "+3 Attack, +3 Defense, +3 Spell Power, +6 Knowledge. Allows the hero to cast the Armageddon spell, and all allied troops are immune to it.",
    "slot": "Weapon",
    "related_artifacts": null,
    "class": "Relic",
    "cost": "50000 G",
    "event_description": "Deep beneath the earth, you find a vault of the Ancients from before the Silence. Inside, you find a sealed casket, deeply etched with dire warnings. Ignoring them, you break the seal. Inside, you find Armageddon's Blade.",
    "how_it_works": "The immunity to Armageddon granted by the blade is not affected by the Orb of Vulnerability.",
    "gameplay_analysis": "Armageddon's Blade is typically banned in multiplayer maps due to its power. Armageddon's Blade is the key artifact in the Armageddon's Blade campaign. In Maker of Sorrows, the artifact is created by the great forgesmith Khazandar by combining several artifacts; however, the blade is not an actual combination artifact.",
    "component_of": null
  },
  {
    "name": "Angel Feather Arrows",
    "effect": "+15% Archery. If the equipped hero does not have the Archery secondary skill, the Angel Feather Arrows has no effect.",
    "slot": "Misc.",
    "related_artifacts": "Bow of the Sharpshooter, Bow of Elven Cherrywood, Bowstring of the Unicorn's Mane",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "Not really wanting to know where the Angel is whose feathers were used for these arrows, you take them and quickly depart.",
    "component_of": "Bow of the Sharpshooter"
  },
  {
    "name": "Angel Wings",
    "effect": "Allows the hero to fly.",
    "slot": "Cape",
    "related_artifacts": "None",
    "class": "Relic",
    "cost": "20000 G",
    "event_description": "Not really wanting to know where the Angel is who belongs to these wings, you take them and quickly depart.",
    "gameplay_analysis": "Angel Wings are typically banned from custom scenarios because they allow the hero to fly over almost anything, including Border Guards and gates.",
    "component_of": null
  },
  {
    "name": "Arms of Legion",
    "effect": "if equipped on a hero stationed in a town at the start of day 1, it increases that town’s level 5 creatures’ growth by +2.",
    "slot": "Misc.",
    "related_artifacts": "Statue of Legion, Head of Legion, Torso of Legion, Loins of Legion, Legs of Legion",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "Searching a ruin, you are amazed to find a piece of the Statue of Legion. You carefully dust it off before placing it in your pack.",
    "component_of": "Statue of Legion"
  },
  {
    "name": "Badge of Courage",
    "effect": "+1 Morale.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Crest of Valor, Glyph of Gallantry, Spirit of Oppression, Pendant of Downfall, Ring of Suppression, Hideous Mask",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "After saving a young boy from a vicious pack of Wolves, you return him to his father's manor. The grateful nobleman awards you with a Badge of Courage.",
    "component_of": null
  },
  {
    "name": "Bird of Perception",
    "effect": "+5% Eagle Eye. If the equipped hero does not have the Eagle Eye secondary skill, the Bird of Perception has no effect.",
    "slot": "Misc.",
    "related_artifacts": "Stoic Watchman, Emblem of Cognizance",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "An old witch who seems to have been expecting you, hands you a small statue and departs, never having said a word.",
    "component_of": null
  },
  {
    "name": "Blackshard of the Dead Knight",
    "effect": "+3 Attack.",
    "slot": "Weapon",
    "related_artifacts": "Armor of the Damned, Skull Helmet, Rib Cage, Shield of the Yawning Dead",
    "class": "Minor",
    "cost": "3000 G",
    "event_description": "The widow of a former Captain of the Guard admires your quest and gives you the enchanted Sword that her husband relied on during his tour of duty.",
    "component_of": "Armor of the Damned"
  },
  {
    "name": "Boots of Levitation",
    "effect": "Allows the hero to use the Water Walk spell.",
    "slot": "Feet",
    "related_artifacts": "None",
    "class": "Relic",
    "cost": "10000 G",
    "event_description": "Visiting a local wise man, you explain the intent of your journey. He reaches into a chest and withdraws a strange pair of boots which he hands to you.",
    "component_of": null
  },
  {
    "name": "Boots of Polarity",
    "effect": "+15% Resistance.",
    "slot": "Feet",
    "related_artifacts": "Pendant of Reflection, Garniture of Interference, Surcoat of Counterpoise",
    "class": "Relic",
    "cost": "6000 G",
    "event_description": "A Nomad trader seeks protection from a tribe of Goblins. For your assistance, he gives you a finely crafted pair of boots made from the softest leather. Looking closely, you see fascinating ancient carvings engraved on the leather.",
    "how_it_works": "The bonus stacks with the hero's Resistance skill or adds it if the skill is not present.",
    "component_of": "Pendant of Reflection"
  },
  {
    "name": "Boots of Speed",
    "effect": "+400 movement points on land.",
    "slot": "Feet",
    "related_artifacts": "Equestrian's Gloves",
    "class": "Minor",
    "cost": "6000 G",
    "event_description": "Visiting a local wise man, you explain the intent of your journey. He reaches into a chest and withdraws a strange pair of boots which he hands to you.",
    "component_of": null
  },
  {
    "name": "Bow of Elven Cherrywood",
    "effect": "+5% Archery. If the equipped hero does not have the Archery secondary skill, the artifact has no effect.",
    "slot": "Misc.",
    "related_artifacts": "Bow of the Sharpshooter, Bowstring of the Unicorn's Mane, Angel Feather Arrows",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "A chance meeting with a famous Archer finds you in a game of knucklebones pitting his bow against your horse. You win.",
    "component_of": "Bow of the Sharpshooter"
  },
  {
    "name": "Bow of the Sharpshooter",
    "effect": "Removes range and obstacle penalties for allied shooters.",
    "slot": "3 Misc.",
    "related_artifacts": "Bow of Elven Cherrywood, Bowstring of the Unicorn's Mane, Angel Feather Arrows",
    "class": "Combination",
    "cost": "12000 G",
    "event_description": "You trip over the Bow of the Sharpshooter, dust it off, and stick it in your pack.",
    "component_of": null
  },
  {
    "name": "Bowstring of the Unicorn's Mane",
    "effect": "+10% Archery. If the equipped hero does not have the Archery secondary skill, the artifact has no effect.",
    "slot": "Misc.",
    "related_artifacts": "Bow of the Sharpshooter, Bow of Elven Cherrywood, Angel Feather Arrows",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "An ensnared Unicorn whinnies in fright. Murmuring soothing words, you set her free. Snorting and stamping her front hoof once, she gallops off. Looking down you see that she dropped what appears to be a finely crafted bowstring.",
    "component_of": "Bow of the Sharpshooter"
  },
  {
    "name": "Breastplate of Brimstone",
    "effect": "+5 Spell Power.",
    "slot": "Torso",
    "related_artifacts": "Armageddon's Blade, Shield of the Damned, Sphere of Permanence",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "You meet a blacksmith who is in the process of melting down old pieces of armor and weapons to reclaim the metal. When he learns of your quest, he gives you a breastplate that he claims refused to melt, and is therefore of no value to him.",
    "component_of": null
  },
  {
    "name": "Breastplate of Petrified Wood",
    "effect": "+1 Spell Power.",
    "slot": "Torso",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "A gang of Rogues is sifting through the possessions of dead warriors. Scaring off the scavengers, you note the Rogues had overlooked a strange breastplate.",
    "component_of": null
  },
  {
    "name": "Buckler of the Gnoll King",
    "effect": "+4 Defense.",
    "slot": "Shield",
    "related_artifacts": "None",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "A stone statue of a warrior holds a silver shield. As you remove the shield, the statue crumbles into dust.",
    "component_of": null
  },
  {
    "name": "Cape of Conjuring",
    "effect": "+3 spell duration.",
    "slot": "Cape",
    "related_artifacts": "Ring of the Magi, Collar of Conjuring, Ring of Conjuring",
    "class": "Treasure",
    "cost": "1500 G",
    "event_description": "Before you appears a levitating glass case with a folded cloak perched upon a bed of crimson velvet. At your touch, the lid opens and the cloak floats into your awaiting hands.",
    "component_of": "Ring of the Magi"
  },
  {
    "name": "Cape of Silence",
    "effect": "Prevents level 1-2 spell casting.",
    "slot": "Cape",
    "related_artifacts": "Recanter's Cloak, Orb of Inhibition",
    "class": "Major",
    "cost": "7500 G",
    "event_description": "As you pass the graveyard, you notice an old man mourning over his wife. As you approach him, the old man falls dead. After burying him, you decide to take his cape.",
    "component_of": null
  },
  {
    "name": "Cape of Velocity",
    "effect": "Allied creatures gain +2 Speed.",
    "slot": "Cape",
    "related_artifacts": "Necklace of Swiftness, Ring of the Wayfarer",
    "class": "Major",
    "cost": "10000 G",
    "event_description": "A brief stop at an improbable rural inn yields an exchange of money, tales, and accidentally, luggage. You find a magical cloak in your new backpack.",
    "component_of": null
  },
  {
    "name": "Cards of Prophecy",
    "effect": "+1 Luck.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Clover of Fortune, Ladybird of Luck, Hourglass of the Evil Hour, Runes of Imminency, Demon's Horseshoe, Shaman's Puppet",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "You meet a traveler who offers to let you draw a card from the strange deck that he carries. When you refuse, he draws one himself. He has a momentary look of surprise on his face, then vanishes with a pop, dropping the cards to the floor. You gather them, and leave.",
    "component_of": null
  },
  {
    "name": "Celestial Necklace of Bliss",
    "effect": "+3 to all Primary Skills.",
    "slot": "Necklace",
    "related_artifacts": "Angelic Alliance, Helm of Heavenly Enlightenment, Armor of Wonder, Sandals of the Saint, Sword of Judgement, Lion's Shield of Courage",
    "class": "Relic",
    "cost": "12000 G",
    "event_description": "After rescuing a Sorceress from a cursed tomb, she rewards your heroism with an exquisite jeweled necklace.",
    "component_of": "Angelic Alliance"
  },
  {
    "name": "Centaur's Axe",
    "effect": "+2 Attack.",
    "slot": "Weapon",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "You see a heavy axe embedded deeply in the ground. After several unsuccessful attempts by your army to remove it, you tightly grip the handle of the axe and effortlessly pull it free.",
    "component_of": null
  },
  {
    "name": "Charm of Eclipse",
    "effect": "-10% enemy Spell Power.",
    "slot": "Misc.",
    "related_artifacts": "Plate of Dying Light, Seal of Sunset",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "While messing around with a curious trinket that you managed to trade something equally unneeded for at a peddler, you find that, although it's made of metal, it doesn't reflect the sun rays, but rather absorbs them readily.",
    "component_of": null
  },
  {
    "name": "Charm of Mana",
    "effect": "Regenerates 1 spell point / day.",
    "slot": "Misc.",
    "related_artifacts": "Wizard's Well, Talisman of Mana, Mystic Orb of Mana",
    "class": "Treasure",
    "cost": "500 G",
    "event_description": "You come upon a caravan of gypsies who are feasting and fortifying their bodies with mead. They call you forward and say, \"If you prove that you can dance the Rama-Buta, we will reward you.\". You don't know it, but try anyway. They laugh hysterically, but admire your bravery, giving you a strange charm.",
    "component_of": "Wizard's Well"
  },
  {
    "name": "Cloak of the Undead King",
    "effect": "(No Skill) 15% of slain troops raised as Skeletons - (Basic) +5% Necromancy, raises Walking Dead - (Advanced) +10% Necromancy, raises Wights - (Expert) +15% Necromancy, raises Liches.",
    "slot": "Necklace, Cape, Feet",
    "related_artifacts": "Amulet of the Undertaker, Vampire's Cowl, Dead Man's Boots",
    "class": "Combination",
    "cost": "12000 G",
    "event_description": "You trip over the Cloak of the Undead King, dust it off, and stick it in your pack.",
    "how_it_works": "For heroes without the Necromancy skill, the cloak raises 15% of killed enemies as Skeletons. For heroes with Necromancy, the power can be increased by a Necromancy Amplifier, Soul Prison, or a hero's Necromancy specialty, but not by the cloak's component artifacts. Upgraded creatures are raised at a reduced rate. If tournament rules are on, the artifact does not work.",
    "component_of": null
  },
  {
    "name": "Clover of Fortune",
    "effect": "+1 Luck.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Cards of Prophecy, Ladybird of Luck, Hourglass of the Evil Hour, Runes of Imminency, Demon's Horseshoe, Shaman's Puppet",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "While walking across a patch of dried vegetation, you are surprised to find a healthy, green four-leaf clover.",
    "component_of": null
  },
  {
    "name": "Collar of Conjuring",
    "effect": "+1 spell duration.",
    "slot": "Necklace",
    "related_artifacts": "Ring of the Magi, Cape of Conjuring, Ring of Conjuring",
    "class": "Treasure",
    "cost": "500 G",
    "event_description": "Before you appears a levitating glass case with a golden choker perched upon a bed of crimson velvet. At your touch, the lid opens and the choker floats into your awaiting hands.",
    "component_of": "Ring of the Magi"
  },
  {
    "name": "Cornucopia",
    "effect": "+5 of each rare resource (M, S, C, G) / day.",
    "slot": "2 Ring, Cape, Misc.",
    "related_artifacts": "Everflowing Crystal Cloak, Ring of Infinite Gems, Eversmoking Ring of Sulfur, Everpouring Vial of Mercury",
    "class": "Combination",
    "cost": "20000 G",
    "event_description": "You trip over the Cornucopia Horn of the Abyss, dust it off, and stick it in your pack.",
    "gameplay_analysis": "In The Shadow of Death , the artifact description refers to it as the \"Town of Plenty\" instead of \"Horn of Plenty\". This is changed to just \"Cornucopia\" in Horn of the Abyss .",
    "component_of": null
  },
  {
    "name": "Crest of Valor",
    "effect": "+1 Morale.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Badge of Courage, Glyph of Gallantry, Spirit of Oppression, Pendant of Downfall, Ring of Suppression, Hideous Mask",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "After freeing a princess of a neighboring kingdom from the evil clutches of despicable slavers, she awards you with a Crest of Valor.",
    "component_of": null
  },
  {
    "name": "Crown of Dragontooth",
    "effect": "+4 Spell Power, +4 Knowledge.",
    "slot": "Helmet",
    "related_artifacts": "Power of the Dragon Father, Necklace of Dragonteeth, Dragon Scale Armor, Dragon Wing Tabard, Dragonbone Greaves, Red Dragon Flame Tongue, Dragon Scale Shield, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Relic",
    "cost": "8000 G",
    "event_description": "While out scaring up game, your troops find a mysterious crown levitating about three feet off of the ground. They hand it to you, and you notice an inscription. It reads: \"Brains best brawn and magic beats might. Heed my words, and you'll win every fight.\"",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Crown of the Five Seas",
    "effect": "+6 Knowledge.",
    "slot": "Helmet",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "7000 G",
    "event_description": "You hardly set a camp, leaving the saddle for the first time for the day, as some critter sneaked up on you and pulled one of your boots in his hole. Swearing silently, you search the hole with your hand. Instead of a boot, you touch something sharp. Amazed, you pull out a crown.",
    "component_of": null
  },
  {
    "name": "Crown of the Supreme Magi",
    "effect": "+4 Knowledge.",
    "slot": "Helmet",
    "related_artifacts": "Ironfist of the Ogre, Tunic of the Cyclops King, Ogre's Club of Havoc, Targ of the Rampaging Ogre",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "A mad wizard who has been terrorizing the region has foolishly chosen you as his target today. Realizing that his power comes from his crown, you take aim with your bow, knocking the crown from his head and releasing him from his crazed madness. Grateful to be free, he lets you keep the crown.",
    "component_of": "Ironfist of the Ogre"
  },
  {
    "name": "Dead Man's Boots",
    "effect": "+7.5% Necromancy. If the equipped hero does not have the Necromancy secondary skill, the Dead Man's Boots has no effect.",
    "slot": "Feet",
    "related_artifacts": "Cloak of the Undead King, Amulet of the Undertaker, Vampire's Cowl",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "Discovering a pair of beautifully beaded boots made from the finest and softest leather, you thank the anonymous donor and add the boots to your inventory.",
    "component_of": "Cloak of the Undead King"
  },
  {
    "name": "Demon's Horseshoe",
    "effect": "-1 enemy Luck.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Cards of Prophecy, Clover of Fortune, Ladybird of Luck, Hourglass of the Evil Hour, Runes of Imminency, Shaman's Puppet",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "During your overnight stay you hear hooves clatter nearby. You look around in darkness and notice a demon's figure, ready to stab you with its horns. You barely survive the attack and keep his horseshoe as a trophy.",
    "component_of": null
  },
  {
    "name": "Diplomat's Cloak",
    "effect": "Increases diplomatic army strength and allows surrender without losing the hero. Allows a hero to ignore the \"Hit and Run\" ban in Horn of the Abyss.",
    "slot": "Misc., Cape, Ring",
    "related_artifacts": "Statesman's Medal, Ambassador's Sash, Diplomat's Ring",
    "class": "Combination",
    "cost": "15000 G",
    "event_description": "You come upon an old blind man stumbling along the road. He says, \"Good hero, I have need of your assistance. I have lost my seeing eye dog. If you could find him for me I would be in your debt.\" You readily agree, and find the dog playing with some Halflings a short distance away. \"Thank you so much,\" he says upon your return. \"I have no money, but please take this cloak as a reward for your kindness.\"",
    "component_of": null
  },
  {
    "name": "Diplomat's Ring",
    "effect": "Reduces the cost of surrendering by 10%.",
    "slot": "Ring",
    "related_artifacts": "Diplomat's Cloak, Statesman's Medal, Ambassador's Sash",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You pause to help a diplomat with a broken axle fix his problem. In gratitude, he gives you a ring with magical properties which he says will, \"help people see things your way.\"",
    "component_of": "Diplomat's Cloak"
  },
  {
    "name": "Dragonbone Greaves",
    "effect": "+1 Spell Power, +1 Knowledge.",
    "slot": "Feet",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Necklace of Dragonteeth, Dragon Scale Armor, Dragon Wing Tabard, Red Dragon Flame Tongue, Dragon Scale Shield, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "You trip over what seem to be the bones of a large Dragon. Upon further examination, you discover the bones to be a pair of greaves.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Dragon Scale Armor",
    "effect": "+4 Attack, +4 Defense.",
    "slot": "Torso",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Necklace of Dragonteeth, Dragon Wing Tabard, Dragonbone Greaves, Red Dragon Flame Tongue, Dragon Scale Shield, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Relic",
    "cost": "8000 G",
    "event_description": "You meet an old Armorer who claims he owes you a favor. Taking him up on it, he pieces together some Dragon scales, forming a well-fashioned breastplate.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Dragon Scale Shield",
    "effect": "+3 Attack, +3 Defense.",
    "slot": "Shield",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Necklace of Dragonteeth, Dragon Scale Armor, Dragon Wing Tabard, Dragonbone Greaves, Red Dragon Flame Tongue, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "You meet an old Armorer who claims he owes you a favor. Taking him up on it, he pieces together some Dragon scales, forming a well-fashioned shield.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Dragon Wing Tabard",
    "effect": "+2 Spell Power, +2 Knowledge.",
    "slot": "Cape",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Necklace of Dragonteeth, Dragon Scale Armor, Dragonbone Greaves, Red Dragon Flame Tongue, Dragon Scale Shield, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "Ridding the countryside of the hideous Dragon who made a sport of eating noblemen's Knights, you are honored with a Dragon Wing Tabard.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Elixir of Life",
    "effect": "All creatures in the hero's army gain +25% Health, Regeneration, and +4 health points.",
    "slot": "2 Ring, Misc.",
    "related_artifacts": "Ring of Life, Ring of Vitality, Vial of Lifeblood",
    "class": "Combination",
    "cost": "20000 G",
    "event_description": "You trip over the Elixir of Life, dust it off, and stick it in your pack.",
    "how_it_works": "The 25% Health bonus is calculated from a creature's base Health and is rounded down. Creatures with a base Health of less than 4 do not get the bonus.",
    "component_of": null
  },
  {
    "name": "Emblem of Cognizance",
    "effect": "+15% Eagle Eye. If the equipped hero does not have the Eagle Eye secondary skill, the Emblem of Cognizance has no effect.",
    "slot": "Misc.",
    "related_artifacts": "Bird of Perception, Stoic Watchman",
    "class": "Minor",
    "cost": "3000 G",
    "event_description": "An old witch who seems to have been expecting you, hands you a small talisman and departs, never having said a word.",
    "component_of": null
  },
  {
    "name": "Endless Bag of Gold",
    "effect": "+750 Gold / day.",
    "slot": "Misc.",
    "related_artifacts": "Golden Goose, Endless Purse of Gold, Endless Sack of Gold",
    "class": "Major",
    "cost": "7500 G",
    "event_description": "A noblewoman, separated from her traveling companions, asks for your help. After escorting her home, she rewards you with a bag filled with gold.",
    "component_of": "Golden Goose"
  },
  {
    "name": "Endless Purse of Gold",
    "effect": "+500 Gold / day.",
    "slot": "Misc.",
    "related_artifacts": "Golden Goose, Endless Bag of Gold, Endless Sack of Gold",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "In your travels, you find a leather purse filled with gold that once belonged to a great warrior king who had the ability to transform any inanimate object into gold.",
    "component_of": "Golden Goose"
  },
  {
    "name": "Endless Sack of Gold",
    "effect": "+1000 Gold / day.",
    "slot": "Misc.",
    "related_artifacts": "Golden Goose, Endless Purse of Gold, Endless Bag of Gold",
    "class": "Relic",
    "cost": "10000 G",
    "event_description": "A little leprechaun dances gleefully around a magic sack. Seeing you approach, he stops in mid-stride. The little man screams and stamps his foot ferociously, vanishing into thin air. Remembering the old leprechaun saying 'Finders Keepers', you grab the sack and leave.",
    "component_of": "Golden Goose"
  },
  {
    "name": "Equestrian's Gloves",
    "effect": "+200 movement points on land.",
    "slot": "Ring",
    "related_artifacts": "Boots of Speed",
    "class": "Minor",
    "cost": "3000 G",
    "event_description": "A brief stop at an improbable rural inn yields an exchange of money, tales, and accidentally, luggage. You find a magical pair of gloves in your new backpack.",
    "component_of": null
  },
  {
    "name": "Everflowing Crystal Cloak",
    "effect": "+1 Crystal / day.",
    "slot": "Cape",
    "related_artifacts": "Cornucopia, Eversmoking Ring of Sulfur, Ring of Infinite Gems, Everpouring Vial of Mercury",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "Taking shelter from a storm in a small cave, you notice a small patch of crystal in one corner. Curious, you discover that the patch is really a cloak, and when you break a piece off it mysteriously grows back. You decide to take the cloak with you.",
    "component_of": "Cornucopia"
  },
  {
    "name": "Everpouring Vial of Mercury",
    "effect": "+1 Mercury / day.",
    "slot": "Misc.",
    "related_artifacts": "Cornucopia, Everflowing Crystal Cloak, Eversmoking Ring of Sulfur, Ring of Infinite Gems",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "A brief stop at a hastily abandoned Wizard's tower turns up a magical vial of mercury that always has a little left on the bottom. Recognizing a treasure when you see one, you cap it and slip it in your pocket.",
    "component_of": "Cornucopia"
  },
  {
    "name": "Eversmoking Ring of Sulfur",
    "effect": "+1 Sulfur / day.",
    "slot": "Ring",
    "related_artifacts": "Cornucopia, Everflowing Crystal Cloak, Ring of Infinite Gems, Everpouring Vial of Mercury",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You visit an alchemist who, upon seeing your army, is swayed by the righteousness of your cause. The newly loyal subject gives you his eversmoking ring of sulfur to help with the war effort.",
    "component_of": "Cornucopia"
  },
  {
    "name": "Garniture of Interference",
    "effect": "+5% Resistance.",
    "slot": "Necklace",
    "related_artifacts": "Pendant of Reflection, Surcoat of Counterpoise, Boots of Polarity",
    "class": "Major",
    "cost": "2000 G",
    "event_description": "You've come upon a fight between a Necromancer and a Paladin. The Necromancer blasts the Paladin with a fire bolt, bringing him to his knees. Acting quickly, you slay the evil one before the final blow. The grateful Paladin gives you the armor that saved him.",
    "how_it_works": "The bonus stacks with the hero's Resistance skill or adds it if the skill is not present.",
    "component_of": "Pendant of Reflection"
  },
  {
    "name": "Glyph of Gallantry",
    "effect": "+1 Morale.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Badge of Courage, Crest of Valor, Spirit of Oppression, Pendant of Downfall, Ring of Suppression, Hideous Mask",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "Ridding the countryside of the hideous Minotaur who made a sport of eating noblemen's Knights, you are honored with the Glyph of Gallantry.",
    "component_of": null
  },
  {
    "name": "Golden Bow",
    "effect": "All allied shooters can attack at any range without penalty.",
    "slot": "Misc.",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "8000 G",
    "event_description": "A chance meeting with a famous Archer finds you in a game of knucklebones pitting his bow against your horse. You win.",
    "component_of": null
  },
  {
    "name": "Golden Goose",
    "effect": "+7000 Gold / day.",
    "slot": "3 Misc.",
    "related_artifacts": "Endless Purse of Gold, Endless Bag of Gold, Endless Sack of Gold",
    "class": "Combination",
    "cost": "22500 G",
    "event_description": "You wander on an abandoned house of a collector in search for a camp place. Most of the goods were long stolen by the marauders, but you were able to find a couple of dusty pet statues. You vaguely recognize one of them. You rub the dust off one of them, and discover a golden goose.",
    "component_of": null
  },
  {
    "name": "Greater Gnoll's Flail",
    "effect": "+4 Attack.",
    "slot": "Weapon",
    "related_artifacts": "None",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "A clumsy Gnoll has killed himself with his own flail. Knowing your superior skill with this weapon, you confidently remove the spectacular flail from the fallen creature.",
    "component_of": null
  },
  {
    "name": "Head of Legion",
    "effect": "if equipped on a hero stationed in a town at the start of day 1, it increases that town’s level 6 creatures’ growth by +1.",
    "slot": "Misc.",
    "related_artifacts": "Statue of Legion, Arms of Legion, Torso of Legion, Loins of Legion, Legs of Legion",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "Searching a ruin, you are amazed to find a piece of the Statue of Legion. You carefully dust it off before placing it in your pack.",
    "component_of": "Statue of Legion"
  },
  {
    "name": "Hellstorm Helmet",
    "effect": "+5 Knowledge.",
    "slot": "Helmet",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "Your army is ambushed by a small tribe of wild (and none too bright) Orcs. You fend them off easily and the survivors flee in all directions. One of the Orcs was wearing a polished horned helm. Figuring it will make a good souvenir, you take it.",
    "component_of": null
  },
  {
    "name": "Helm of Chaos",
    "effect": "+3 Knowledge.",
    "slot": "Helmet",
    "related_artifacts": "None",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "Your army is ambushed by a small tribe of wild (and none too bright) Orcs. You fend them off easily and the survivors flee in all directions. One of the Orcs was wearing a polished horned helm. Figuring it will make a good souvenir, you take it.",
    "component_of": null
  },
  {
    "name": "Helm of Heavenly Enlightenment",
    "effect": "+6 to all Primary Skills.",
    "slot": "Helmet",
    "related_artifacts": "Angelic Alliance, Celestial Necklace of Bliss, Armor of Wonder, Sandals of the Saint, Sword of Judgement, Lion's Shield of Courage",
    "class": "Relic",
    "cost": "24000 G",
    "event_description": "You spy a gleaming object poking up out of the ground. You send a member of your party over to investigate. He comes back with a golden helmet in his hands. You realize that it must be the Helm of Heavenly Enlightenment, the only helm ever rumored to be made from solid gold.",
    "component_of": "Angelic Alliance"
  },
  {
    "name": "Helm of the Alabaster Unicorn",
    "effect": "+1 Knowledge.",
    "slot": "Helmet",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "A traveling tinker in need of supplies offers you a helm with a unicorn's horn on its top in exchange for food and water. Curious, you accept, and later find out that the helm is magical.",
    "component_of": null
  },
  {
    "name": "Hideous Mask",
    "effect": "-1 to ally and enemy Morale.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Badge of Courage, Crest of Valor, Glyph of Gallantry, Spirit of Oppression, Pendant of Downfall, Ring of Suppression",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "You meet a traveling circus on your way. One of the artists had such a deft disguise that you have drawn a sword, ready to defend yourself. It appeared that a pretty actress was hiding behind the mask. Laughing, she gifts you the mask.",
    "component_of": null
  },
  {
    "name": "Horn of the Abyss",
    "effect": "After every combat, revives a number of slain enemy troops as Fangarms. This artifact is banned by default.",
    "slot": "Misc.",
    "related_artifacts": "None",
    "class": "Relic",
    "cost": "50000 G",
    "event_description": "This waterfall sounds and looks exactly like a waterfall should. On closer inspection, though, you are amazed to find out the flow is headed upwards. You wonder what it took for such an impressive phenomenon to come into being. Surely a powerful artifact has to be in play? And indeed, an ornate horn is soon found levitating above the crest.",
    "how_it_works": "The total Hit Points of the raised Fangarm stack will be half of the slain stack's total Hit Points, but the quantity of Fangarms will not exceed half the number of creatures in the slain stack. The effect is not affected by the Ring of Oblivion or any spell-restricting artifacts or map objects. While equipped, Necromancy cannot raise Undead creatures.",
    "component_of": null
  },
  {
    "name": "Hourglass of the Evil Hour",
    "effect": "Negates ally and enemy Luck bonuses.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Cards of Prophecy, Clover of Fortune, Ladybird of Luck, Runes of Imminency, Demon's Horseshoe, Shaman's Puppet",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "A surprise turn in the landscape finds you in the midst of a grisly scene - vultures picking at the aftermath of a terrible battle. Your cursory search of the remains turns up an enchanted hourglass.",
    "component_of": null
  },
  {
    "name": "Inexhaustible Cart of Lumber",
    "effect": "+1 Wood / day.",
    "slot": "Misc.",
    "related_artifacts": "Inexhaustible Cart of Ore",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "Pausing to rest and light a cook fire, you pull wood out of a nearby lumber cart. As you keep pulling wood from the cart, you notice that its cargo doesn't shrink. You realize to your delight that the cart is enchanted, so you take it along.",
    "how_it_works": "Equipping multiple carts will grant additional wood equal to the number of carts equipped.",
    "component_of": null
  },
  {
    "name": "Inexhaustible Cart of Ore",
    "effect": "+1 Ore / day.",
    "slot": "Misc.",
    "related_artifacts": "Inexhaustible Cart of Lumber",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "You've found a Goblin weapon smithy making weapons for use against humans. With a tremendous yell you and your army descend upon their camp and drive them away. A search finds a magic cart that never runs out of ore.",
    "how_it_works": "Equipping multiple carts will grant additional ore equal to the number of carts equipped.",
    "component_of": null
  },
  {
    "name": "Ironfist of the Ogre",
    "effect": "+5 Attack, +5 Defense, +4 Spell Power, +4 Knowledge. Casts Expert Haste, Bloodlust, Fire Shield, and Counterstrike for 50 rounds on all allied troops at the start of combat.",
    "slot": "Helmet, Torso, Weapon, Shield",
    "related_artifacts": "Crown of the Supreme Magi, Tunic of the Cyclops King, Ogre's Club of Havoc, Targ of the Rampaging Ogre",
    "class": "Combination",
    "cost": "20000 G",
    "event_description": "On passing by a small cave you hear deep thumping. You enter the cave and see a juvenile Cyclops cracking nuts with an enormous hammer. Every strike ends in shells and nut pieces being scattered all over the cave. You teach the Cyclops to crack nuts more sparingly by crushing them against each other. Overjoyed with this lesson, the youth gifts you the hammer.",
    "how_it_works": "The spell-casting ability can be mitigated by creature immunities, Cursed Ground, or anti-magic artifacts, but works in Anti-Magic Garrisons. The specialties of heroes Cyra, Terek, Brissa, Ash, and Inteus affect the spells cast by the artifact.",
    "component_of": null
  },
  {
    "name": "Ladybird of Luck",
    "effect": "+1 Luck.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Cards of Prophecy, Clover of Fortune, Hourglass of the Evil Hour, Runes of Imminency, Demon's Horseshoe, Shaman's Puppet",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "An old witch who seems to have been expecting you, hands you a small statue and departs, never having said a word.",
    "component_of": null
  },
  {
    "name": "Legs of Legion",
    "effect": "if equipped on a hero stationed in a town at the start of day 1, it increases that town’s level 2 creatures’ growth by +5.",
    "slot": "Misc.",
    "related_artifacts": "Statue of Legion, Head of Legion, Arms of Legion, Torso of Legion, Loins of Legion",
    "class": "Treasure",
    "cost": "5000 G",
    "event_description": "Searching a ruin, you are amazed to find a piece of the Statue of Legion. You carefully dust it off before placing it in your pack.",
    "component_of": "Statue of Legion"
  },
  {
    "name": "Lion's Shield of Courage",
    "effect": "+4 to all Primary Skills.",
    "slot": "Shield",
    "related_artifacts": "Angelic Alliance, Helm of Heavenly Enlightenment, Celestial Necklace of Bliss, Armor of Wonder, Sandals of the Saint, Sword of Judgement",
    "class": "Relic",
    "cost": "16000 G",
    "event_description": "You've come upon a fight between a Necromancer and a Paladin. The Necromancer blasts the Paladin with a fire bolt, bringing him to his knees. Acting quickly, you slay the evil one before the final blow. The grateful Paladin gives you the shield that saved him.",
    "component_of": "Angelic Alliance"
  },
  {
    "name": "Loins of Legion",
    "effect": "if equipped on a hero stationed in a town at the start of day 1, it increases that town’s level 3 creatures’ growth by +4.",
    "slot": "Misc.",
    "related_artifacts": "Statue of Legion, Head of Legion, Arms of Legion, Torso of Legion, Legs of Legion",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "Searching a ruin, you are amazed to find a piece of the Statue of Legion. You carefully dust it off before placing it in your pack.",
    "component_of": "Statue of Legion"
  },
  {
    "name": "Mystic Orb of Mana",
    "effect": "Regenerates 3 spell points / day.",
    "slot": "Misc.",
    "related_artifacts": "Wizard's Well, Charm of Mana, Talisman of Mana",
    "class": "Treasure",
    "cost": "1500 G",
    "event_description": "You come upon a caravan of gypsies who are feasting and fortifying their bodies with mead. They call you forward and say, \"If you prove that you can dance the Rama-Buta, we will reward you.\" You don't know it, but try anyway. They laugh hysterically, but admire your bravery, giving you a strange orb.",
    "component_of": "Wizard's Well"
  },
  {
    "name": "Necklace of Dragonteeth",
    "effect": "+3 Spell Power, +3 Knowledge.",
    "slot": "Necklace",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Dragon Scale Armor, Dragon Wing Tabard, Dragonbone Greaves, Red Dragon Flame Tongue, Dragon Scale Shield, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "An old shaman stands in the road before you, screaming something in a language you can't understand. He suddenly vanishes in a cloud of smoke. When the smoke clears, there is a long string of Dragon teeth in the spot where he was standing.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Necklace of Ocean Guidance",
    "effect": "+1000 movement points at sea.",
    "slot": "Necklace",
    "related_artifacts": "Admiral's Hat, Sea Captain's Hat",
    "class": "Major",
    "cost": "10000 G",
    "event_description": "An old sea captain is being tortured by Ogres. You save him, and in return he rewards you with a wondrous necklace that will guide you at sea.",
    "component_of": "Admiral's Hat"
  },
  {
    "name": "Necklace of Swiftness",
    "effect": "Allied creatures gain +1 Speed.",
    "slot": "Necklace",
    "related_artifacts": "Cape of Velocity, Ring of the Wayfarer",
    "class": "Treasure",
    "cost": "5000 G",
    "event_description": "Visiting a local wise man, you explain the intent of your journey. He reaches into a sack and withdraws a strange necklace which he hands to you.",
    "component_of": null
  },
  {
    "name": "Ogre's Club of Havoc",
    "effect": "+5 Attack.",
    "slot": "Weapon",
    "related_artifacts": "Ironfist of the Ogre, Crown of the Supreme Magi, Tunic of the Cyclops King, Targ of the Rampaging Ogre",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "At a roadside tavern, a drunken Ogre challenges you to a fight. Not wanting to hurt the creature, you subdue him instead, and take his massive club from him to prevent him from getting into any more trouble.",
    "component_of": "Ironfist of the Ogre"
  },
  {
    "name": "Orb of Driving Rain",
    "effect": "Increases the damage of all Water Magic spells by 50%.",
    "slot": "Misc.",
    "related_artifacts": "Orb of the Firmament, Orb of Silt, Orb of Tempestuous Fire",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a strange orb of the elements.",
    "how_it_works": "This artifact affects Magic Arrow, Ice Bolt, and Frost Ring.",
    "component_of": null
  },
  {
    "name": "Orb of Inhibition",
    "effect": "Prevents all spell casting in combat.",
    "slot": "Misc.",
    "related_artifacts": "Recanter's Cloak, Cape of Silence",
    "class": "",
    "cost": "G",
    "event_description": "",
    "how_it_works": "It prevents almost all creature spell casting, such as an Archangel's Resurrection ability. It does not prevent Faerie Dragon spell casting or spell casting from artifacts like Armor of the Damned or Angelic Alliance.",
    "component_of": null
  },
  {
    "name": "Orb of Silt",
    "effect": "Increases the damage of all Earth Magic spells by 50%.",
    "slot": "Misc.",
    "related_artifacts": "Orb of the Firmament, Orb of Tempestuous Fire, Orb of Driving Rain",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a strange orb of the elements.",
    "how_it_works": "This artifact affects Magic Arrow, Death Ripple, Meteor Shower, and Implosion.",
    "component_of": null
  },
  {
    "name": "Orb of the Firmament",
    "effect": "Increases the damage of all Air Magic spells by 50%.",
    "slot": "Misc.",
    "related_artifacts": "Orb of Silt, Orb of Tempestuous Fire, Orb of Driving Rain",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a strange orb of the elements.",
    "how_it_works": "This artifact affects Magic Arrow, Lightning Bolt, Destroy Undead, Chain Lightning, and Titan's Lightning Bolt.",
    "component_of": null
  },
  {
    "name": "Orb of Tempestuous Fire",
    "effect": "Increases the damage of all Fire Magic spells by 50%.",
    "slot": "Misc.",
    "related_artifacts": "Orb of the Firmament, Orb of Silt, Orb of Driving Rain",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a strange orb of the elements.",
    "how_it_works": "This artifact affects Magic Arrow, Fire Wall, Fireball, Land Mine, Armageddon, Inferno, and Fire Shield.",
    "component_of": null
  },
  {
    "name": "Orb of Vulnerability",
    "effect": "Negates all creature magic immunities.",
    "slot": "Misc.",
    "related_artifacts": "None",
    "class": "Relic",
    "cost": "25000 G",
    "event_description": "You meet an old Wizard friend of yours traveling in the opposite direction. He presents you with a gift: An orb that allows nearby magic resistant creatures to be harmed by magic.",
    "how_it_works": "The orb also negates the Resistance secondary skill and magic resistance from creature abilities and artifacts. It does not negate Golem's spell damage resistance.",
    "gameplay_analysis": "Gives a huge advantage against creatures with strong magical resistance but can be a double-edged sword by stripping allied troops of their immunities. For example, Black Dragons can be resurrected with the Orb.",
    "component_of": null
  },
  {
    "name": "Pendant of Courage",
    "effect": "+3 Luck and +3 Morale.",
    "slot": "Necklace",
    "related_artifacts": "Still Eye of the Dragon, Badge of Courage, Crest of Valor, Glyph of Gallantry, Spirit of Oppression, Pendant of Downfall, Ring of Suppression, Hideous Mask, Cards of Prophecy, Clover of Fortune, Ladybird of Luck, Hourglass of the Evil Hour, Runes of Imminency, Demon's Horseshoe, Shaman's Puppet",
    "class": "Major",
    "cost": "7000 G",
    "event_description": "Responding to cries for help, you find river Sprites making a sport of dunking an old man. Feeling vengeful, you rescue the man and drag a Sprite onto dry land for a while. The Sprite, uncomfortable in the air, gives you a magic pendant to let him go.",
    "component_of": null
  },
  {
    "name": "Pendant of Death",
    "effect": "Immunity to Destroy Undead.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "2500 G",
    "event_description": "A quick and deadly battle with a Necromancer wins you his magical pendant. Later, a Wizard tells you that the pendant protects undead under your control from spells meant to destroy them.",
    "component_of": null
  },
  {
    "name": "Pendant of Dispassion",
    "effect": "Immunity to Berserk.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "The sound of combat draws you to the scene of a fight between an old Barbarian and an eight-headed Hydra. Your timely intervention swings the battle in favor of the man, and he rewards you with a pendant he used to use to calm his mind for battle.",
    "component_of": null
  },
  {
    "name": "Pendant of Downfall",
    "effect": "-2 enemy Morale.",
    "slot": "Necklace",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Spirit of Oppression, Ring of Suppression, Hideous Mask",
    "class": "Major",
    "cost": "7000 G",
    "event_description": "You visit the jeweler's shop. You land your eyes on a bracelet, but the shopkeeper immediately warns you that it is cursed. You fear no curses, and put the bracelet on immediately. The bracelet vanishes in a flash. Enraged, you are about to kill the shopkeeper, but he offers you the Pendant of Downfall in return. You agree.",
    "component_of": null
  },
  {
    "name": "Pendant of Free Will",
    "effect": "Immunity to Hypnotize.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "A brief roadside encounter with a small caravan and a game of knucklebones wins a magic pendant. Its former owner says that it protects against hypnosis.",
    "component_of": null
  },
  {
    "name": "Pendant of Holiness",
    "effect": "Immunity to Curse.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "In your wanderings you come across a hermit living in a small, tidy hut. Impressed with your mission, he takes time out from his meditations to bless and give you a charm against curses.",
    "component_of": null
  },
  {
    "name": "Pendant of Life",
    "effect": "Immunity to Death Ripple.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "2500 G",
    "event_description": "A fierce windstorm reveals the entrance to a buried tomb. Your investigation reveals that the tomb has already been looted, but the thieves overlooked an ankh on a gold chain in the dark.",
    "gameplay_analysis": "This artifact should probably be assigned to your best scout, making them less liable to lose their army before they can retreat from a superior enemy force.",
    "component_of": null
  },
  {
    "name": "Pendant of Negativity",
    "effect": "Immunity to Lightning Bolt and Chain Lightning. Does not provide immunity to Titan's Lightning Bolt.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You come upon the remains of a small hut which was clearly destroyed by a very large bolt of lightning. Sifting through the debris, you find an undamaged pendant that seems to tingle in your hand.",
    "component_of": null
  },
  {
    "name": "Pendant of Reflection",
    "effect": "+50% magic resistance.",
    "slot": "Necklace, Cape, Feet",
    "related_artifacts": "Garniture of Interference, Surcoat of Counterpoise, Boots of Polarity",
    "class": "Combination",
    "cost": "12000 G",
    "event_description": "Soldiers approach you with talks about a miracle. You are intrigued and follow them. You see a strange sight indeed; a wanderer sitting on top of the fire trap, without any harm. You offer him money in exchange for the secret, but he laughs and vanishes in the air. You see a strange pendant left in the middle of the trap.",
    "how_it_works": "The bonus stacks with the hero's Resistance skill or adds it if the skill is not present. The Orb of Vulnerability can negate its effect.",
    "component_of": null
  },
  {
    "name": "Pendant of Second Sight",
    "effect": "Immunity to Blind.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You come upon a very old woman, long blind from cataracts and dying alone. You tend to her final needs and promise a proper burial. Grateful, she gives you a magic pendant emblazoned with a stylized eye. It lets you see with your eyes closed.",
    "component_of": null
  },
  {
    "name": "Pendant of Total Recall",
    "effect": "Immunity to Forgetfulness.",
    "slot": "Necklace",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "3000 G",
    "event_description": "Alongside the remains of a burnt witch lies a beautiful pendant, intricately designed. Approaching the corpse with caution, you add the item to your inventory.",
    "component_of": null
  },
  {
    "name": "Plate of Dying Light",
    "effect": "-25% enemy Spell Power.",
    "slot": "Torso",
    "related_artifacts": "Seal of Sunset, Charm of Eclipse",
    "class": "Relic",
    "cost": "10000 G",
    "event_description": "The goblin you met at the tavern is acting incredibly brazenly, and the reason for that is obviously the luxurious armor on his chest. It becomes apparent quickly that the armor offers poor protection from a good kick in the ass, yet it still is good for something - but how would a dumb goblin know that?",
    "component_of": null
  },
  {
    "name": "Power of the Dragon Father",
    "effect": "+16 to all Primary Skills, +1 Luck, +1 Morale. All creatures in the hero's army become immune to level 1-4 spells.",
    "slot": "Helmet, Necklace, Torso, Weapon, Cape, Feet, Shield, 2 Ring",
    "related_artifacts": "Crown of Dragontooth, Necklace of Dragonteeth, Dragon Scale Armor, Dragon Wing Tabard, Dragonbone Greaves, Red Dragon Flame Tongue, Dragon Scale Shield, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Combination",
    "cost": "42000 G",
    "event_description": "You trip over the Power of the Dragon Father, dust it off, and stick it in your pack.",
    "gameplay_analysis": "The immunity to level 1-4 spells prevents the hero from casting beneficial spells like Resurrection on their own troops, but it does not stop the enemy from using Implosion. It is an extremely powerful \"Dragogeddon\" enabler.",
    "component_of": null
  },
  {
    "name": "Quiet Eye of the Dragon",
    "effect": "+1 Attack and +1 Defense.",
    "slot": "Ring",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Necklace of Dragonteeth, Dragon Scale Armor, Dragon Wing Tabard, Dragonbone Greaves, Red Dragon Flame Tongue, Dragon Scale Shield, Still Eye of the Dragon",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "While venturing into a decrepit hut you find the skeleton of a long dead witch. Investigation of the remains reveals a ring with a Dragon's eye set into it.",
    "how_it_works": "Equipping two Quiet Eyes of the Dragon provides +2 Attack and +2 Defense.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Recanter's Cloak",
    "effect": "Prevents level 3-4-5 spell casting.",
    "slot": "Cape",
    "related_artifacts": "Cape of Silence, Orb of Inhibition",
    "class": "Major",
    "cost": "8000 G",
    "event_description": "Responding to the panicked cries of a damsel in distress, you discover a young woman fleeing from a hungry bear. You slay the beast in the nick of time, and the grateful Sorceress weaves a magic cloak from the bear's hide.",
    "component_of": null
  },
  {
    "name": "Red Dragon Flame Tongue",
    "effect": "+2 Attack, +2 Defense.",
    "slot": "Weapon",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Necklace of Dragonteeth, Dragon Scale Armor, Dragon Wing Tabard, Dragonbone Greaves, Dragon Scale Shield, Quiet Eye of the Dragon, Still Eye of the Dragon",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "As you are walking along a narrow path, a nearby bush suddenly bursts into flames. Before your eyes the flames become the image of a beautiful woman. She holds out a magnificent sword to you.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Rib Cage",
    "effect": "+2 Spell Power.",
    "slot": "Torso",
    "related_artifacts": "Armor of the Damned, Skull Helmet, Blackshard of the Dead Knight, Shield of the Yawning Dead",
    "class": "Minor",
    "cost": "3000 G",
    "event_description": "You trip over what was the rib cage of a large creature. Upon further examination, you discover the rib cage to be a piece of armor.",
    "component_of": "Armor of the Damned"
  },
  {
    "name": "Ring of Conjuring",
    "effect": "+2 spell duration.",
    "slot": "Ring",
    "related_artifacts": "Ring of the Magi, Collar of Conjuring, Cape of Conjuring",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "You find a small tree that closely resembles the great Warlock, Brimstone, with a ring around one of its twigs. Scraps of clothing and rotting leather lead you to suspect that it IS Brimstone, transformed. Since you can't help him, you take the magic ring.",
    "component_of": "Ring of the Magi"
  },
  {
    "name": "Ring of Infinite Gems",
    "effect": "+1 Gem / day.",
    "slot": "Ring",
    "related_artifacts": "Cornucopia, Everflowing Crystal Cloak, Eversmoking Ring of Sulfur, Everpouring Vial of Mercury",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "A cry of pain leads you to a Centaur, caught in a trap. Upon setting the creature free, he hands you a small pouch. Emptying the contents, you find a dazzling jeweled ring.",
    "component_of": "Cornucopia"
  },
  {
    "name": "Ring of Life",
    "effect": "All creatures in your army gain +1 Health.",
    "slot": "Ring",
    "related_artifacts": "Elixir of Life, Ring of Vitality, Vial of Lifeblood",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "While pausing to rest, you notice a bobcat climbing a short tree to get at a crow's nest. On impulse, you climb the tree yourself and scare off the cat. When you look in the nest, you find a collection of shiny stones and a ring.",
    "gameplay_analysis": "Pretty useful for a minor artifact. Can do wonders for your first level units.",
    "component_of": "Elixir of Life"
  },
  {
    "name": "Ring of Oblivion",
    "effect": "While equipped, corpses disappear immediately after a unit's death.",
    "slot": "Ring",
    "related_artifacts": "None",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "While pausing to rest, you notice a bobcat climbing a short tree to get at a crow's nest. On impulse, you climb the tree yourself and scare off the cat. When you look in the nest, you find a collection of shiny stones and a ring.",
    "how_it_works": "This prevents Resurrection, Animate Dead, Sacrifice, and Devour Corpses from working. Vampirism and Repair restore health but do not revive units. Necromancy raises no undead after battle.",
    "component_of": null
  },
  {
    "name": "Ring of Suppression",
    "effect": "-1 enemy Morale.",
    "slot": "Ring",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Badge of Courage, Crest of Valor, Glyph of Gallantry, Spirit of Oppression, Pendant of Downfall, Hideous Mask",
    "class": "Treasure",
    "cost": "4000 G",
    "event_description": "You ordered fried eggs for breakfast. The cook managed to find the eggs for you. He also found a ring in the bird's nest that he passed to you.",
    "component_of": null
  },
  {
    "name": "Ring of the Magi",
    "effect": "Increases the duration of all hero's spells by 50 rounds.",
    "slot": "Necklace, Cape, Ring",
    "related_artifacts": "Collar of Conjuring, Cape of Conjuring, Ring of Conjuring",
    "class": "Combination",
    "cost": "3000 G",
    "event_description": "You trip over the Ring of the Magi, dust it off, and stick it in your pack.",
    "component_of": null
  },
  {
    "name": "Ring of the Wayfarer",
    "effect": "Allied creatures gain +1 Speed.",
    "slot": "Ring",
    "related_artifacts": "Necklace of Swiftness, Cape of Velocity",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "Visiting a local wise man, you explain the intent of your journey. He reaches into a sack and withdraws a strange ring which he hands to you.",
    "component_of": null
  },
  {
    "name": "Ring of Vitality",
    "effect": "All creatures in your army gain +1 Health.",
    "slot": "Ring",
    "related_artifacts": "Elixir of Life, Ring of Life, Vial of Lifeblood",
    "class": "Treasure",
    "cost": "5000 G",
    "event_description": "While pausing to rest, you notice a bobcat climbing a short tree to get at a crow's nest. On impulse, you climb the tree yourself and scare off the cat. When you look in the nest, you find a collection of shiny stones and a ring.",
    "gameplay_analysis": "Ring of Vitality is quite useful for a treasure class artifact. While it only increases health by one point, it can still mean +33% for some first level troops.",
    "component_of": "Elixir of Life"
  },
  {
    "name": "Royal Armor of Nix",
    "effect": "+6 to Spell Power.",
    "slot": "Torso",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "7000 G",
    "event_description": "You see a fight on a hill nearby. As you get closer, you see two nix. One is winning, and as he is about to land a finishing blow, you intervene. The defeated nix thanks you for your help, and gifts you with his armor. He believes you deserve it more than he does.",
    "component_of": null
  },
  {
    "name": "Runes of Imminency",
    "effect": "-1 enemy Luck.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Cards of Prophecy, Clover of Fortune, Ladybird of Luck, Hourglass of the Evil Hour, Demon's Horseshoe, Shaman's Puppet",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "Close by, on a mountain edge you see a mage trying to cast a spell. Fiery symbols are already flashing in the sky, when he, while blinded by the light, trips and falls down. The mage perishes, and you gather the chain of mysterious stones in your backpack.",
    "component_of": null
  },
  {
    "name": "Sandals of the Saint",
    "effect": "+2 to all Primary Skills.",
    "slot": "Feet",
    "related_artifacts": "Angelic Alliance, Helm of Heavenly Enlightenment, Celestial Necklace of Bliss, Armor of Wonder, Sword of Judgement, Lion's Shield of Courage",
    "class": "Relic",
    "cost": "8000 G",
    "event_description": "A Nomad trader seeks protection from a tribe of Goblins. For your assistance, he gives you a finely crafted pair of sandals made from the softest leather. Looking closely, you see fascinating ancient carvings engraved on the leather.",
    "component_of": "Angelic Alliance"
  },
  {
    "name": "Scales of the Greater Basilisk",
    "effect": "+3 Spell Power.",
    "slot": "Torso",
    "related_artifacts": "None",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "You meet an old Armorer who claims he owes you a favor. Taking him up on it, he pieces together some Basilisk scales, forming a well-fashioned breastplate.",
    "component_of": null
  },
  {
    "name": "Sea Captain's Hat",
    "effect": "Allows casting Summon Boat and Scuttle Boat at the expert level. Protects from whirlpools. Increases sea movement by 500 points.",
    "slot": "Helmet",
    "related_artifacts": "Admiral's Hat, Necklace of Ocean Guidance",
    "class": "Relic",
    "cost": "15000 G",
    "event_description": "An old seaman tells you a tale of an enchanted hat that he used in his youth to rally his crew into fits of efficiency. He then hands you a faded map that shows where he hid it. After much exploring, you find it stashed underneath a nearby rock.",
    "component_of": "Admiral's Hat"
  },
  {
    "name": "Seal of Sunset",
    "effect": "-20% enemy Spell Power.",
    "slot": "Ring",
    "related_artifacts": "Plate of Dying Light, Charm of Eclipse",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "It's never nice to get hit in the noggin by a fist with a heavy ring on the finger. Still, that's what happened to you in a friendly sparring with an old hero acquaintance, and after that, you couldn't manage the simplest spell to relieve dizziness for quite a while. During the booze-up after the sparring, the ring migrated over to your digit.",
    "component_of": null
  },
  {
    "name": "Sentinel's Shield",
    "effect": "+12 Defense, -3 Attack.",
    "slot": "Shield",
    "related_artifacts": "Titan's Thunder, Thunder Helmet, Titan's Cuirass, Titan's Gladius",
    "class": "Relic",
    "cost": "10000 G",
    "event_description": "You find a large box that seems to be made from some unknown metal. When you touch it, the box opens with a loud hiss, revealing a gleaming shield within.",
    "component_of": "Titan's Thunder"
  },
  {
    "name": "Shackles of War",
    "effect": "Prevents both heroes from retreating or surrendering.",
    "slot": "Misc.",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "Walking through the ruins of an ancient walled city, you find the instrument of the city's destruction, the elaborately crafted Shackles of War.",
    "gameplay_analysis": "While excellent for killing enemy heroes, it can be a double-edged sword. It's best to equip it just before a battle you intend to win and remove it afterward. It is useful against computer-controlled scouts who tend to retreat immediately. In Horn of the Abyss, the effect is only active in hero-to-hero battles.",
    "component_of": null
  },
  {
    "name": "Shaman's Puppet",
    "effect": "-1 to enemy Luck and Morale.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Cards of Prophecy, Clover of Fortune, Ladybird of Luck, Hourglass of the Evil Hour, Runes of Imminency, Demon's Horseshoe",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "The day looked not so great from the beginning. You walked under the ladder, met a woman with an empty bucket and stepped on a black cat. Apparently, it is not your misfortune, but the guy in rugs who has been following you. You order to seize the loser, but he runs away. As he vanishes, you notice a strange doll that he dropped.",
    "component_of": null
  },
  {
    "name": "Shield of Naval Glory",
    "effect": "+6 Defense.",
    "slot": "Shield",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "7000 G",
    "event_description": "You meet an old admiral at the tavern. After a couple of hours full of tales about glorious battles and days long passed he gifts you his parade shield.",
    "component_of": null
  },
  {
    "name": "Shield of the Dwarven Lords",
    "effect": "+2 Defense.",
    "slot": "Shield",
    "related_artifacts": "None",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "While searching through the rubble of a caved-in mine, you free a group of trapped Dwarves. Grateful, the leader gives you a finely crafted shield.",
    "component_of": null
  },
  {
    "name": "Shield of the Yawning Dead",
    "effect": "+3 Defense.",
    "slot": "Shield",
    "related_artifacts": "Armor of the Damned, Skull Helmet, Rib Cage, Blackshard of the Dead Knight",
    "class": "Minor",
    "cost": "3000 G",
    "event_description": "Your troops discover an eerie shrine dedicated to the Undead. You bless the shrine, causing the stone shield emblem above the altar to crack. Underneath it is a real shield, which you decide to separate from this unholy place.",
    "component_of": "Armor of the Damned"
  },
  {
    "name": "Skull Helmet",
    "effect": "+2 Knowledge.",
    "slot": "Helmet",
    "related_artifacts": "Armor of the Damned, Rib Cage, Blackshard of the Dead Knight, Shield of the Yawning Dead",
    "class": "Treasure",
    "cost": "3000 G",
    "event_description": "A brief stop at an improbable rural inn yields an exchange of money, tales, and accidentally, luggage. You find a magical helm in your new backpack.",
    "component_of": "Armor of the Damned"
  },
  {
    "name": "Sleepkeeper",
    "effect": "Immunity to mind spells. This artifact is banned by default.",
    "slot": "Misc.",
    "related_artifacts": "None",
    "class": "Relic",
    "cost": "50000 G",
    "event_description": "You are seeing the same dream for the third night already. A stranger begs you to buy an enchanted broom. You refuse every time, but the dream repeats night by night. You ask the first witch doctor you meet for help, but instead of a potion he gives you a plain statuette, ensuring that it will solve your problem. (continued below)",
    "gameplay_analysis": "The Sleepkeeper has the same effect as the hidden effect of the Badge of Courage. It also provided immunity to mind spells, but this effect was removed in Horn of the Abyss.",
    "component_of": null
  },
  {
    "name": "Speculum",
    "effect": "+1 Scouting radius.",
    "slot": "Misc.",
    "related_artifacts": "Spyglass",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "A merchant from far away lands trades you a new invention of his people for traveling supplies. It makes distant objects appear closer, and he calls it... a Speculum.",
    "component_of": null
  },
  {
    "name": "Spellbinder's Hat",
    "effect": "Allows the hero to cast all level 5 spells.",
    "slot": "Helmet",
    "related_artifacts": "Tomes of Magic (Air, Earth, Fire, Water)",
    "class": "Relic",
    "cost": "30000 G",
    "event_description": "You see a Wizard fleeing from a Dragon and riding like the wind. The Wizard opens a portal and rides through, getting his hat knocked off by the edge of the gate. The Dragon follows, and the gate closes. You pick the hat up, dust it off, and put it on.",
    "how_it_works": "Spells can be cast even if the hero lacks the required Wisdom level or a Spell Book. Spells banned by the mapmaker are not available.",
    "gameplay_analysis": "The artifact is highly useful for providing access to Dimension Door and Implosion. The spell selection is asymmetrical across magic schools; for example, it does not provide the powerful level 4 adventure spells Town Portal or Water Walk.",
    "component_of": null
  },
  {
    "name": "Sphere of Permanence",
    "effect": "Makes the hero's troops immune to the Dispel spell.",
    "slot": "Misc.",
    "related_artifacts": null,
    "class": "Major",
    "cost": "7500 G",
    "event_description": "You meet an old Wizard friend of yours traveling in the opposite direction. He presents you with a gift: An orb that prevents the use of the dispel magic spell on your allies.",
    "gameplay_analysis": "The artifact's true power is shown when fighting enemy heroes with expert Dispel. You can freely use buffs on your troops, knowing that the enemy cannot remove them.",
    "component_of": null
  },
  {
    "name": "Spirit of Oppression",
    "effect": "Negates all ally and enemy Morale bonuses.",
    "slot": "Misc.",
    "related_artifacts": "Pendant of Courage, Still Eye of the Dragon, Badge of Courage, Crest of Valor, Glyph of Gallantry, Pendant of Downfall, Ring of Suppression, Hideous Mask",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "Walking through the ruins of an ancient walled city, you find the instrument of the city's destruction, the Spirit of Oppression.",
    "how_it_works": "Also negates effects from morale-altering spells like Mirth and Sorrow.",
    "gameplay_analysis": "This artifact is very useful for armies with no morale-boosting skills or items, and is especially effective for Necropolis and Conflux. Against neutral stacks, it prevents them from getting extra turns.",
    "component_of": null
  },
  {
    "name": "Statesman's Medal",
    "effect": "Reduces the cost of surrendering by 10%.",
    "slot": "Necklace",
    "related_artifacts": "Diplomat's Cloak, Ambassador's Sash, Diplomat's Ring",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You pause to help a diplomat with a broken axle fix his problem. In gratitude, he gives you a medal with magical properties which he says will, \"help people see things your way.\"",
    "component_of": "Diplomat's Cloak"
  },
  {
    "name": "Statue of Legion",
    "effect": "Increases the growth of creatures in all allied towns by 50%; if the Statue is equipped on a hero stationed in a town at the start of day 1, it increases that town’s creature’s growth by +1 level 6, +2 level 5, +3 level 4, +4 level 3, and +5 level 2 creatures.",
    "slot": "5 Misc.",
    "related_artifacts": "Head of Legion, Arms of Legion, Torso of Legion, Loins of Legion, Legs of Legion",
    "class": "Combination",
    "cost": "25000 G",
    "event_description": "You trip over the Statue of Legion, dust it off, and stick it in your pack.",
    "how_it_works": "A player can only have one active Statue of Legion at a time; a second one only provides the component effects. It is affected by the Grail bonus but not by flagged external dwellings. Two identical pieces do not stack on one hero, but they do stack if one is on a garrisoned hero and the other is on a visiting hero in the same town.",
    "component_of": null
  },
  {
    "name": "Still Eye of the Dragon",
    "effect": "+1 Luck and +1 Morale.",
    "slot": "Ring",
    "related_artifacts": "Power of the Dragon Father, Crown of Dragontooth, Necklace of Dragonteeth, Dragon Scale Armor, Dragon Wing Tabard, Dragonbone Greaves, Red Dragon Flame Tongue, Dragon Scale Shield, Quiet Eye of the Dragon",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "While venturing into a decrepit hut you find the skeleton of a long dead witch. Investigation of the remains reveals a ring with a Dragon's eye set into it.",
    "component_of": "Power of the Dragon Father"
  },
  {
    "name": "Stoic Watchman",
    "effect": "+10% Eagle Eye. If the equipped hero does not have the Eagle Eye secondary skill, the Stoic Watchman has no effect.",
    "slot": "Misc.",
    "related_artifacts": "Bird of Perception, Emblem of Cognizance",
    "class": "Treasure",
    "cost": "2000 G",
    "event_description": "An old witch who seems to have been expecting you, hands you a small statue and departs, never having said a word.",
    "component_of": null
  },
  {
    "name": "Surcoat of Counterpoise",
    "effect": "+10% Resistance.",
    "slot": "Cape",
    "related_artifacts": "Pendant of Reflection, Garniture of Interference, Boots of Polarity",
    "class": "Major",
    "cost": "4000 G",
    "event_description": "You've come upon a fight between a Necromancer and a Paladin. The Necromancer blasts the Paladin with a fire bolt, bringing him to his knees. Acting quickly, you slay the evil one before the final blow. The grateful Paladin gives you the cloak that saved him.",
    "how_it_works": "The bonus stacks with the hero's Resistance skill or adds it if the skill is not present.",
    "component_of": "Pendant of Reflection"
  },
  {
    "name": "Sword of Hellfire",
    "effect": "+6 Attack.",
    "slot": "Weapon",
    "related_artifacts": "Armageddon's Blade, Breastplate of Brimstone, Shield of the Damned, Sphere of Permanence",
    "class": "Major",
    "cost": "6000 G",
    "event_description": "During a sudden storm, a bolt of lightning strikes a tree, splitting it. Inside the tree you find a mysterious sword.",
    "component_of": null
  },
  {
    "name": "Sword of Judgement",
    "effect": "+5 to all Primary Skills.",
    "slot": "Weapon",
    "related_artifacts": "Angelic Alliance, Helm of Heavenly Enlightenment, Celestial Necklace of Bliss, Armor of Wonder, Sandals of the Saint, Lion's Shield of Courage",
    "class": "Relic",
    "cost": "20000 G",
    "event_description": "You come upon a battle where a Paladin has been mortally wounded by a group of Zombies. He asks you to take his sword and finish what he started. As you pick it up, it begins to hum, and then everything becomes a blur. The Zombies lie dead, the sword dripping with blood. You strap it to your belt.",
    "component_of": "Angelic Alliance"
  },
  {
    "name": "Talisman of Mana",
    "effect": "Regenerates 2 spell points / day.",
    "slot": "Misc.",
    "related_artifacts": "Wizard's Well, Charm of Mana, Mystic Orb of Mana",
    "class": "Treasure",
    "cost": "1000 G",
    "event_description": "You come upon a caravan of gypsies who are feasting and fortifying their bodies with mead. They call you forward and say, \"If you prove that you can dance the Rama-Buta, we will reward you.\" You don't know it, but try anyway. They laugh hysterically, but admire your bravery, giving you a strange talisman.",
    "component_of": "Wizard's Well"
  },
  {
    "name": "Targ of the Rampaging Ogre",
    "effect": "+5 Defense.",
    "slot": "Shield",
    "related_artifacts": "Ironfist of the Ogre, Crown of the Supreme Magi, Tunic of the Cyclops King, Ogre's Club of Havoc",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You come upon a bridge spanning a dry gully. As you begin to cross, a gigantic, maddened Ogre appears from the other side and charges, forcing you to slay it. You decide to take its shield as a trophy.",
    "component_of": "Ironfist of the Ogre"
  },
  {
    "name": "Thunder Helmet",
    "effect": "+10 Knowledge, -2 Spell Power.",
    "slot": "Helmet",
    "related_artifacts": "Titan's Thunder, Titan's Cuirass, Titan's Gladius, Sentinel's Shield",
    "class": "Relic",
    "cost": "10000 G",
    "event_description": "A glint of golden light catches your eye. Upon further investigation, you find a golden helm hidden under a bush.",
    "component_of": "Titan's Thunder"
  },
  {
    "name": "Titan's Cuirass",
    "effect": "+12 Spell Power, -2 Knowledge.",
    "slot": "Torso",
    "related_artifacts": "Titan's Thunder, Thunder Helmet, Titan's Gladius, Sentinel's Shield",
    "class": "Relic",
    "cost": "10000 G",
    "event_description": "A Titan stops you and says, \"Pay me 5,000 gold, or I shall slay you where you stand.\" You refuse. The Titan grabs the sword hanging from its belt, but you duck between its legs. He is so surprised by this maneuver that he trips... falling on his sword and killing himself instantly. You relieve him of his belongings.",
    "component_of": "Titan's Thunder"
  },
  {
    "name": "Titan's Gladius",
    "effect": "+12 Attack, -3 Defense.",
    "slot": "Weapon",
    "related_artifacts": "Titan's Thunder, Thunder Helmet, Titan's Cuirass, Sentinel's Shield",
    "class": "Relic",
    "cost": "10000 G",
    "event_description": "A Titan stops you and says, \"Pay me 5,000 gold, or I shall slay you where you stand.\" You refuse. The Titan grabs the sword hanging from its belt, but you duck between its legs. He is so surprised by this maneuver that he trips... falling on his sword and killing himself instantly.",
    "component_of": "Titan's Thunder"
  },
  {
    "name": "Titan's Thunder",
    "effect": "+9 Attack, +9 Defense, +8 Spell Power, +8 Knowledge. Allows casting of Titan's Lightning Bolt, and gives the hero a Spell Book.",
    "slot": "Helmet, Torso, Weapon, Shield",
    "related_artifacts": "Thunder Helmet, Titan's Cuirass, Titan's Gladius, Sentinel's Shield",
    "class": "Combination",
    "cost": "40000 G",
    "event_description": "You trip over the Titan's Thunder, dust it off, and stick it in your pack.",
    "component_of": null
  },
  {
    "name": "Tome of Air Magic",
    "effect": "When equipped, provides all Air Magic spells.",
    "slot": "Misc.",
    "related_artifacts": "Tome of Earth Magic, Tome of Fire Magic, Tome of Water Magic",
    "class": "Relic",
    "cost": "20000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a copy of a book of the elements.",
    "how_it_works": "Spells banned by the mapmaker are not available in the Tome.",
    "component_of": null
  },
  {
    "name": "Tome of Earth Magic",
    "effect": "When equipped, provides all Earth Magic spells.",
    "slot": "Misc.",
    "related_artifacts": "Tome of Air Magic, Tome of Fire Magic, Tome of Water Magic",
    "class": "Relic",
    "cost": "20000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a copy of a book of the elements.",
    "how_it_works": "Spells banned by the mapmaker are not available in the Tome.",
    "component_of": null
  },
  {
    "name": "Tome of Fire Magic",
    "effect": "When equipped, provides all Fire Magic spells.",
    "slot": "Misc.",
    "related_artifacts": "Tome of Air Magic, Tome of Earth Magic, Tome of Water Magic",
    "class": "Relic",
    "cost": "20000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a copy of a book of the elements.",
    "how_it_works": "Spells banned by the mapmaker are not available in the Tome.",
    "component_of": null
  },
  {
    "name": "Tome of Water Magic",
    "effect": "When equipped, provides all Water Magic spells.",
    "slot": "Misc.",
    "related_artifacts": "Tome of Air Magic, Tome of Earth Magic, Tome of Fire Magic",
    "class": "Relic",
    "cost": "20000 G",
    "event_description": "You come across a conjurer who begs to accompany you and your army awhile for safety. You agree, and he offers as payment a copy of a book of the elements.",
    "how_it_works": "Spells banned by the mapmaker are not available in the Tome.",
    "component_of": null
  },
  {
    "name": "Torso of Legion",
    "effect": "if equipped on a hero stationed in a town at the start of day 1, it increases that town’s level 3 creatures’ growth by +4.",
    "slot": "Misc.",
    "related_artifacts": "Statue of Legion, Head of Legion, Arms of Legion, Loins of Legion, Legs of Legion",
    "class": "Minor",
    "cost": "5000 G",
    "event_description": "Searching a ruin, you are amazed to find a piece of the Statue of Legion. You carefully dust it off before placing it in your pack.",
    "component_of": "Statue of Legion"
  },
  {
    "name": "Trident of Dominion",
    "effect": "+7 Attack.",
    "slot": "Weapon",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "7000 G",
    "event_description": "You finally found a well after a long search. Your soldiers could not get the bucket of water out, however. Something was preventing it from coming out. Your banner carrier had to descend in the well himself. It appeared that a trident was blocking the way.",
    "component_of": null
  },
  {
    "name": "Tunic of the Cyclops King",
    "effect": "+4 Spell Power.",
    "slot": "Torso",
    "related_artifacts": "Ironfist of the Ogre, Crown of the Supreme Magi, Ogre's Club of Havoc, Targ of the Rampaging Ogre",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You catch a Cyclops skinny dipping, and as a prank you make off with his clothes. Later, you realize the tunic is magical",
    "component_of": "Ironfist of the Ogre"
  },
  {
    "name": "Vampire's Cowl",
    "effect": "+5% Necromancy. If the equipped hero does not have the Necromancy secondary skill, the Vampire's Cowl has no effect.",
    "slot": "Cape",
    "related_artifacts": "Cloak of the Undead King, Amulet of the Undertaker, Dead Man's Boots",
    "class": "Minor",
    "cost": "4000 G",
    "event_description": "You manage to find a Vampire's resting place during the day, and are able to slay him easily. Just for good measure, you take his cowl.",
    "component_of": "Cloak of the Undead King"
  },
  {
    "name": "Vial of Dragon Blood",
    "effect": "+5 Attack +5 Defense for all allied Dragons.",
    "slot": "Misc.",
    "related_artifacts": "None",
    "class": "Relic",
    "cost": "20000 G",
    "event_description": "You find a cave guarded by an ancient dragon. After a fierce battle, you slay him. Dragon blood supposedly has magical properties, so you carefully gather some in a vial.",
    "component_of": null
  },
  {
    "name": "Vial of Lifeblood",
    "effect": "All creatures in your army gain +2 Health.",
    "slot": "Misc.",
    "related_artifacts": "Elixir of Life, Ring of Life, Ring of Vitality",
    "class": "Major",
    "cost": "10000 G",
    "event_description": "You find a mystical shrine hidden among the trees. Floating above the altar is a Vial said to contain the blood of life. You very carefully remove it, taking care not to disturb anything else",
    "component_of": "Elixir of Life"
  },
  {
    "name": "Wayfarer's Boots",
    "effect": "Reduces the cost of moving one tile to 100 on any terrain.",
    "slot": "Feet",
    "related_artifacts": "None",
    "class": "Major",
    "cost": "5000 G",
    "event_description": "You meet a wanderer in rugs on a shallow path. He offers you to exchange your cape for his old boots. You agree without much enthusiasm. As he disappears over the horizon you realize the advantage of the transaction",
    "component_of": null
  },
  {
    "name": "Wizard's Well",
    "effect": "Regenerates all spell points at the start of every day.",
    "slot": "3 Misc.",
    "related_artifacts": "Charm of Mana, Talisman of Mana, Mystic Orb of Mana",
    "class": "Combination",
    "cost": "3000 G",
    "event_description": "You trip over the Wizard's Well, dust it off, and stick it in your pack.",
    "gameplay_analysis": "This is a fairly easy combination artifact to assemble. It is more useful than the Ring of the Magi, especially for heroes who can cast expensive spells like Dimension Door or Town Portal repeatedly.",
    "component_of": null
  }
];
